[package]
name = "dsl_wasm"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
dsl_runtime = { path = "../dsl_runtime" }
serde_json = { path = "../serde_json" }
